"""Generate the benchmark's PUBLIC interface documents from their single sources (orchestrator side).

    uv run --project phase4 python scripts/p4/make_public_docs.py

Writes
    benchmarks/causal_state_v1/docs/PROTOCOL_V2.md   research/phase4/INTERFACES.md sections 1-4 + 8, the family rules
                                                     (brainir_causal.families module docstring) and the capability-record fields
    benchmarks/causal_state_v1/docs/API.md           INTERFACES.md sections 5-7 + the api.py module docstring and signatures
Both are generic (no history, no results, no names); the room builder's content scanner checks them again.
"""

from __future__ import annotations

import inspect
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "phase4" / "src"))

from brainir_causal import api, families  # noqa: E402

OUT = ROOT / "benchmarks" / "causal_state_v1" / "docs"

CAPABILITY_FIELDS = """## Capability records (fields)

Every system record carries `capability` (what can be intervened on and at which magnitudes) and `split` (which families
development may use). Fields (absent = not supported):

| key | fields |
|---|---|
| `kick` | `supported`, `moderate` (m_s: the magnitude class unit), `max` (development maximum = 3 m_s), `hi_range` ([lo, hi] of `kick.hi`) |
| `current` | `supported`, `moderate`, `max`, `hi_range`, `pulse_max_duration` (a finite current up to this duration is a PULSE), `sustained_min_duration` (a current at least this long, or persistent, is SUSTAINED) |
| `current_seq` | `supported`, `moderate`, `max`, `min_seg_steps` (minimum segment length in samples) |
| `silence` | `supported` |
| `edge_scale` | `supported`, `moderate` (weakening depth 1 - factor), `factor_range` |
| `param` | `supported`, `fields` (gain / threshold / tau), `moderate` per field |
| `init` | `state` (explicit initial microstates allowed), `restart` (restarts from stored trajectories), `units`, `max_value` |
| `stimulus` | `channels`, `nominal_level`, `max_onset`, `range` (development input range), `allow_zero` |
| `params` | `public_seed_max`, `nominal_seed` (null: every trajectory draws its own parameters) |
| `weight_noise`, `obs_noise` | `max_sd` in development |
| `timing` | `dt_allowed`, `t_end_max` in development |

Magnitude classes (PROTOCOL.md section 3): below detection 0.1 m_s, weak 0.3 m_s, moderate m_s, strong 3 m_s (= the development
maximum); `*.hi` families use 1.5-3 x the development maximum and are never development families.
"""


def sections(text: str) -> dict[int, str]:
    parts = re.split(r"(?m)^(?=## \d+\. )", text)
    out = {}
    for p in parts:
        m = re.match(r"## (\d+)\. ", p)
        if m:
            out[int(m.group(1))] = p.rstrip() + "\n"
    return out


def main() -> int:
    src = (ROOT / "research" / "phase4" / "INTERFACES.md").read_text(encoding="utf-8")
    sec = sections(src)
    OUT.mkdir(parents=True, exist_ok=True)
    fam_doc = inspect.getdoc(families) or ""
    proto = ("# Protocol format, intervention families and system records (`p4-protocol-1`)\n\n"
             "Public interface document of the benchmark `causal_state_v1` (generated by scripts/p4/make_public_docs.py; do not edit).\n\n"
             + "\n".join(sec[i] for i in (1, 2, 3, 4, 8) if i in sec)
             + "\n## Family classification rules (`brainir_causal.families.family_of`)\n\n```\n" + fam_doc + "\n```\n\n" + CAPABILITY_FIELDS)
    api_doc = inspect.getdoc(api) or ""
    sigs = []
    for cls in (api.CausalStateModel, api.CausalStateMethod, api.Designer):
        sigs.append(f"### `{cls.__name__}`\n\n{inspect.getdoc(cls) or ''}\n")
        for name, fn in cls.__dict__.items():
            if callable(fn) and not name.startswith("_"):
                doc = (inspect.getdoc(fn) or "").strip()
                sigs.append(f"- `{name}{inspect.signature(fn)}`" + (f": {doc}" if doc else ""))
        sigs.append("")
    apimd = ("# Model, method and designer API (`brainir_causal.api`)\n\n"
             "Public interface document of the benchmark `causal_state_v1` (generated by scripts/p4/make_public_docs.py; do not edit).\n\n"
             "```\n" + api_doc + "\n```\n\n" + "\n".join(sec[i] for i in (5, 6, 7) if i in sec)
             + "\n## Signatures\n\n" + "\n".join(sigs) + "\n## Config keys\n\n"
             + "\n".join(f"- `{k}`: {v}" for k, v in api.CONFIG_KEYS.items()) + "\n")
    for name, text in (("PROTOCOL_V2.md", proto), ("API.md", apimd)):
        bad = re.findall(r"(?i)phase ?3|phase ?2|previous benchmark|C:[\\/]Dev", text)
        assert not bad, f"{name}: forbidden text {bad[:5]}"
        (OUT / name).write_text(text, encoding="utf-8", newline="\n")
        print("wrote", (OUT / name).relative_to(ROOT), len(text), "chars")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
