"""Generate docs/schema.md from the canonical table specs (docs always match code).

Run:  uv run python scripts/gen_schema_docs.py          (tests/test_docs.py fails if the file is stale)
"""

from __future__ import annotations

import sys

from brainir import paths
from brainir.schema.evidence import EVIDENCE_DESCRIPTIONS, EvidenceKind
from brainir.schema.tables import CANONICAL_TABLES, SCHEMA_VERSION
from brainir.schema.vocab import SIGN_RULE_ID, SIGN_RULES

OUT = paths.repo_root() / "docs" / "schema.md"

HEADER = f"""# BrainIR canonical schema (v{SCHEMA_VERSION})

> Generated by `scripts/gen_schema_docs.py` from `src/brainir/schema/`. Do not edit by hand.

## Principles

1. **Namespacing.** Every record belongs to one `(dataset, dataset_version)`. The global neuron key is
   `neuron_uid = "<dataset>:<version>:<source_id>"`. Native integer IDs are unique only inside one release:
   MANC and MaleCNS share 19,344 integer body IDs that denote different neurons, and CAVE root IDs change with edits.
2. **Evidence kinds are explicit.** Every column carries Arrow field metadata `evidence` (below), so a predicted
   neurotransmitter can never be mistaken for measured physiology, and anatomy is never mistaken for a model
   parameter.
3. **Anatomy is not strength.** `synapse_count` counts T-bar→PSD pairs. There is **no** `weight` column anywhere in
   the anatomy tables. Effective weights are `ModelParameter` records owned by a model.
4. **Hypotheses are computed, not stored.** Excitatory/inhibitory sign is derived on demand from predicted
   neurotransmitters under a versioned rule (`{SIGN_RULE_ID}`) and always reported with that rule ID.
5. **Nothing is silently dropped.**
   - Synapses outside primary neuropils go to `<unassigned>`.
   - Autapses are flagged, not removed.
   - Connectivity to non-neuron fragments is kept in per-neuron totals.

## Evidence kinds
"""

FOOTER = """
## Record models (pydantic, `brainir.schema.models`)

**Core records**
- `DatasetVersion`: dataset, version, release date, animal sex, CNS coverage, acquisition source and method,
  timestamps, checksums, transformations, synapse-confidence thresholds, coordinate space, voxel size, citation,
  license.
- `Neuron`: identity plus curated annotations, `NeurotransmitterPrediction` (ML), `SignHypothesis` (rule-derived),
  neuropil counts, verbatim source annotations, `MorphologyRef` (skeleton/mesh URIs), and `Provenance`.
- `DirectedConnection`: `synapse_count`, `synapse_count_hp`, `is_autapse`, per-neuropil counts and an optional
  `predicted_sign` (the presynaptic neuron's hypothesis; Dale's principle assumed). It has **no weight field**.
- `Synapse`: pre/post locations, detector confidences, neuropil.
- `ModelParameter`: a parameter of a named model, with `origin ∈ {assumed, fitted, derived_from_anatomy}` and its
  derivation.

**Future experiments.** `Experiment` → `Trial` → `Intervention` / `Measurement` / `TimeSeries` / `TargetSpec`.
- Interventions cover optogenetic, thermogenetic, chronic, genetic, pharmacological, electrical, sensory and
  in-silico cases.
- Targets name cell types and neuron UIDs, and also the driver line with a mapping confidence (a genetic line is
  not a neuron).

## Accommodating other connectomes (planned tables; see research/data_ecosystem.md)

| need | planned representation |
|---|---|
| CAVE root-ID churn (FlyWire, BANC, FANC) | `neuron_anchors` (supervoxel / nucleus / anchor point per materialization) + `id_lineage` (old→new) |
| detector / filter as part of version | `DatasetVersion.synapse_table_id` + filter parameters; edges stored unthresholded |
| different neuropil sets and assignment rules | long `connection_neuropils` table + per-dataset ROI catalogue with `all_parents` (DAG) |
| NT class sets and aggregation methods differ | `nt_prediction(level, class_set, class, prob, method, model_id)` long table |
| cross-dataset identity | `cross_dataset_matches(key_a, key_b, level, method, score, source)` (many-to-many) |
| no canonical type ontology | `canonical_types` (synonyms, FBbt IDs) + raw→canonical vocabulary maps with provenance |
| same specimen, several datasets (optic-lobe ⊂ MaleCNS) | `specimen_id` on `DatasetVersion` |
"""


def render() -> str:
    lines = [HEADER]
    lines += ["| kind | meaning |", "|---|---|"]
    for k in EvidenceKind:
        lines.append(f"| `{k.value}` | {EVIDENCE_DESCRIPTIONS[k]} |")
    lines += ["", f"## Sign rule `{SIGN_RULE_ID}`", "", "| NT | sign | class | rationale |", "|---|---|---|---|"]
    for r in SIGN_RULES.values():
        lines.append(f"| {r.nt} | {'' if r.sign is None else f'{r.sign:+d}'} | {r.rule_class} | {r.rationale} |")
    lines += ["", "## Tables", ""]
    for name, spec in CANONICAL_TABLES.items():
        lines += [f"### `{name}`", "", spec.description, "",
                  f"Primary key: `{', '.join(spec.primary_key)}` · sort order: `{', '.join(spec.sort_by)}`", "",
                  "| column | type | null | evidence | unit | description |", "|---|---|---|---|---|---|"]
        for c in spec.columns:
            desc = c.description.replace("|", "\\|")
            lines.append(f"| `{c.name}` | `{c.type}` | {'yes' if c.nullable else 'no'} | {c.evidence.value} | "
                         f"{c.unit or ''} | {desc} |")
        lines.append("")
    lines.append(FOOTER)
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(render(), encoding="utf-8", newline="\n")
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
