#!/usr/bin/env bash
# sbx: run a command inside the Docker sandbox of room @ROOM_NAME@ (Phase 4 clean-room rule: ALL code runs here, never on the host).
#
#   sbx python runs/<prefix>/exp.py --seed 1       # any command of the sandbox image (python, pytest, bash scripts, ...)
#   sbx pytest -q tests/methods
#   sbx --ps                                        # this room's running sandbox containers
#   sbx --stop <container id or name>               # stop one of this room's sandbox containers
#
# What the container sees: the room (mounted at /room; the room's public files read-only, the work areas read-write) and the
# image's pinned Python stack; nothing else. No network. Root file system read-only; /tmp is private and in memory. Creating links
# (symbolic or hard) is refused by the seccomp profile. The working directory inside the container is the room-relative directory
# sbx is called from. Caps: P4_SBX_CPUS (default 2, max @MAX_CPUS@), P4_SBX_MEM_GB (default 6, max @MAX_MEM_GB@),
# P4_SBX_TIMEOUT_S (default 21600 = 6 h, max 43200): the command is stopped after the timeout.
#
# Generated by scripts/make_phase4_cleanroom.py. This copy lives OUTSIDE the room (the launcher puts its directory on PATH); agents
# cannot modify it.
set -euo pipefail
export MSYS_NO_PATHCONV=1 MSYS2_ARG_CONV_EXCL='*'
ROOM_POSIX='@ROOM_POSIX@'
ROOM_MOUNT='@ROOM_MOUNT@'
ROOM_NAME='@ROOM_NAME@'
IMAGE='@IMAGE_ID@'
DOCKER='@DOCKER@'
SECCOMP='@SECCOMP@'
MAX_CPUS=@MAX_CPUS@
MAX_MEM_GB=@MAX_MEM_GB@
# room-relative paths mounted read-only (the allowlisted public files) and work areas re-mounted read-write beneath them
RO_PATHS=(@RO_PATHS@)
RW_PATHS=(@RW_PATHS@)

die() { echo "sbx: $*" >&2; exit 2; }
num() { [[ "$1" =~ ^[0-9]+([.][0-9]+)?$ ]]; }

cpus="${P4_SBX_CPUS:-2}"; mem="${P4_SBX_MEM_GB:-6}"; tmo="${P4_SBX_TIMEOUT_S:-21600}"
num "$cpus" || die "P4_SBX_CPUS must be a number"
num "$mem" || die "P4_SBX_MEM_GB must be a number"
[[ "$tmo" =~ ^[0-9]+$ ]] || die "P4_SBX_TIMEOUT_S must be an integer number of seconds"
awk -v c="$cpus" -v m="$MAX_CPUS" 'BEGIN { exit !(c > 0 && c <= m) }' || die "P4_SBX_CPUS must be in (0, $MAX_CPUS]"
awk -v c="$mem" -v m="$MAX_MEM_GB" 'BEGIN { exit !(c >= 1 && c <= m) }' || die "P4_SBX_MEM_GB must be in [1, $MAX_MEM_GB]"
[ "$tmo" -ge 1 ] && [ "$tmo" -le 43200 ] || die "P4_SBX_TIMEOUT_S must be in [1, 43200]"
threads=$(awk -v c="$cpus" 'BEGIN { t = int(c); if (t < c) t++; if (t < 1) t = 1; print t }')
agent="${P4_AGENT_NAME:-unknown}"
[[ "$agent" =~ ^[A-Za-z0-9_.-]+$ ]] || agent="unknown"

if [ "${1:-}" = "--ps" ]; then
  exec "$DOCKER" ps --filter "label=brainir.p4.room=$ROOM_NAME" \
    --format 'table {{.ID}}\t{{.Names}}\t{{.Label "brainir.p4.agent"}}\t{{.RunningFor}}\t{{.Status}}'
fi
if [ "${1:-}" = "--stop" ]; then
  [ $# -eq 2 ] || die "usage: sbx --stop <container id or name>"
  [[ "$2" =~ ^[A-Za-z0-9_.-]+$ ]] || die "invalid container reference"
  lbl=$("$DOCKER" inspect --format '{{index .Config.Labels "brainir.p4.room"}}' "$2" 2>/dev/null || true)
  [ "$lbl" = "$ROOM_NAME" ] || die "not a sandbox container of this room"
  exec "$DOCKER" stop --timeout 10 "$2"
fi
[ $# -ge 1 ] || die "usage: sbx <command> [args...]   (e.g. sbx python runs/<prefix>/exp.py)"
case "$1" in -*) die "the first argument is the command to run in the sandbox (options belong to that command)";; esac

here="$(pwd -P)"
shopt -s nocasematch
case "$here" in
  "$ROOM_POSIX") rel="" ;;
  "$ROOM_POSIX"/*) rel="${here:${#ROOM_POSIX}}" ;;
  *) die "run sbx from inside the room" ;;
esac
shopt -u nocasematch

mounts=(--mount "type=bind,source=$ROOM_MOUNT,target=/room")
for p in "${RO_PATHS[@]}"; do
  [ -e "$ROOM_POSIX/$p" ] || continue
  mounts+=(--mount "type=bind,source=$ROOM_MOUNT/$p,target=/room/$p,readonly")
done
for p in "${RW_PATHS[@]}"; do
  [ -d "$ROOM_POSIX/$p" ] || continue
  mounts+=(--mount "type=bind,source=$ROOM_MOUNT/$p,target=/room/$p")
done

name="p4sbx-${ROOM_NAME}-${agent}-$$-${RANDOM}"
exec "$DOCKER" run --rm -i --pull never --name "$name" \
  --network none --read-only --tmpfs /tmp:rw,exec,nosuid,size=4g \
  --cap-drop ALL --security-opt no-new-privileges --security-opt "seccomp=$SECCOMP" --pids-limit 512 --user 1000:1000 \
  --cpus "$cpus" --memory "${mem}g" --memory-swap "${mem}g" \
  --label "brainir.p4.room=$ROOM_NAME" --label "brainir.p4.agent=$agent" \
  "${mounts[@]}" -w "/room$rel" \
  -e PYTHONPATH=/room/src -e P4_SANDBOX=1 -e "P4_AGENT_NAME=$agent" -e "P4_SBX_CPUS=$cpus" \
  -e "OMP_NUM_THREADS=$threads" -e "MKL_NUM_THREADS=$threads" -e "OPENBLAS_NUM_THREADS=$threads" \
  "$IMAGE" timeout --signal=TERM --kill-after=30 "$tmo" "$@"
