#!/usr/bin/env bash
# sbx: run a command inside the Docker sandbox of room @ROOM_NAME@ (Phase 4 clean-room rule: ALL code runs here, never on the host).
#
#   sbx python runs/<prefix>/exp.py --seed 1       # any command of the sandbox image (python, pytest, bash scripts, ...)
#   sbx pytest -q tests/methods
#   sbx --ps                                        # YOUR running sandbox containers in this room
#   sbx --stop <container id or name>               # stop one of YOUR sandbox containers in this room
#
# What the container sees: the room, mounted READ-ONLY at /room, with only the work areas bound read-write over it, and the image's
# pinned Python stack; nothing else. Work areas: @WORK_DOC@ (<agent> = the launcher's --scratch, default the agent's name). In a
# shared area (<area>/<agent>) every agent writes only its own subdirectory and reads the others' (read-only); private areas show
# only the agent's own subdirectory. Python writes no bytecode into the room (PYTHONDONTWRITEBYTECODE=1, caches under
# /tmp/pyc). No network. Root file system read-only; /tmp is private and in memory. Creating links (symbolic or hard) is refused by
# the seccomp profile. The working directory inside the container is the room-relative directory sbx is called from. Caps:
# P4_SBX_CPUS (default 2, max @MAX_CPUS@), P4_SBX_MEM_GB (default 6, max @MAX_MEM_GB@), P4_SBX_TIMEOUT_S (default 1800 = 30 min,
# max 3600 = 1 h; the machine's single slot must not be held longer): the command is stopped after the timeout.
#
# ONE SANDBOX AT A TIME ON THIS MACHINE (the machine owner's rule): every room's wrapper shares @MAX_SLOTS@ machine-wide slot(s).
# A sandbox starts only when fewer than @MAX_SLOTS@ sandbox containers (any room, any agent) exist and the host has at least
# @MIN_FREE_GB@ GB of free memory; otherwise sbx WAITS (P4_SBX_WAIT_S, default 540 s, max 3600) and then exits with code 75,
# saying how long the slot has been busy (and naming YOUR container if you hold it; other agents' containers are never named).
# Long computations belong on the remote runner, not in the local sandbox; split long local runs into parts under 1 h.
#
# Generated by scripts/make_phase4_cleanroom.py. Agents run the copy OUTSIDE the room (C:\Dev\BrainIR_p4audit\sbx_bin\<room>\sbx, first
# on PATH) with the bare command `sbx`; the room guard refuses every path spelling of sbx and checks this file's hash on every call.
# Both copies are immutable for agents (NTFS deny ACE).
set -euo pipefail
export MSYS_NO_PATHCONV=1 MSYS2_ARG_CONV_EXCL='*'
ROOM_POSIX='@ROOM_POSIX@'
ROOM_MOUNT='@ROOM_MOUNT@'
ROOM_NAME='@ROOM_NAME@'
IMAGE='@IMAGE_ID@'
DOCKER='@DOCKER@'
SECCOMP='@SECCOMP@'
MAX_CPUS=@MAX_CPUS@
MAX_MEM_GB=@MAX_MEM_GB@
FREE_ROOM=@FREE_ROOM@
# work areas bound read-write (rooms with declared work areas; created by the builder)
RW_PATHS=(@RW_PATHS@)
# per-agent areas: /room/<area> is a private, read-only in-memory directory holding only <area>/<agent>, bound read-write
AGENT_AREAS=(@AGENT_AREAS@)
# shared areas owned per agent: /room/<area> stays read-only (every agent's subdirectory readable), <area>/<agent> bound read-write
OWNED_AREAS=(@OWNED_AREAS@)
# the simulation-service token of each agent (written by the launcher OUTSIDE the room; forwarded into the container only)
TOKEN_DIR='@TOKEN_DIR@'
# top-level entries that belong to the orchestrator (never bound read-write; free rooms bind every OTHER top-level entry)
RO_TOPS=(@RO_TOPS@)
# the machine-wide sandbox slot (outside every room): at most MAX_SLOTS sandbox containers at once, started only above MIN_FREE_GB
SLOT_DIR='@SLOT_DIR@'
MAX_SLOTS=@MAX_SLOTS@
MIN_FREE_GB=@MIN_FREE_GB@

die() { echo "sbx: $*" >&2; exit 2; }
num() { [[ "$1" =~ ^[0-9]+([.][0-9]+)?$ ]]; }

cpus="${P4_SBX_CPUS:-2}"; mem="${P4_SBX_MEM_GB:-6}"; tmo="${P4_SBX_TIMEOUT_S:-1800}"; wait_s="${P4_SBX_WAIT_S:-540}"
num "$cpus" || die "P4_SBX_CPUS must be a number"
num "$mem" || die "P4_SBX_MEM_GB must be a number"
[[ "$tmo" =~ ^[0-9]+$ ]] || die "P4_SBX_TIMEOUT_S must be an integer number of seconds"
[[ "$wait_s" =~ ^[0-9]+$ ]] && [ "$wait_s" -le 3600 ] || die "P4_SBX_WAIT_S must be an integer number of seconds in [0, 3600]"
awk -v c="$cpus" -v m="$MAX_CPUS" 'BEGIN { exit !(c > 0 && c <= m) }' || die "P4_SBX_CPUS must be in (0, $MAX_CPUS]"
awk -v c="$mem" -v m="$MAX_MEM_GB" 'BEGIN { exit !(c >= 1 && c <= m) }' || die "P4_SBX_MEM_GB must be in [1, $MAX_MEM_GB]"
[ "$tmo" -ge 1 ] && [ "$tmo" -le 3600 ] || die "P4_SBX_TIMEOUT_S must be in [1, 3600] (the machine's single sandbox slot; split longer runs or use the remote runner)"
threads=$(awk -v c="$cpus" 'BEGIN { t = int(c); if (t < c) t++; if (t < 1) t = 1; print t }')
agent="${P4_AGENT_NAME:-unknown}"
[[ "$agent" =~ ^[A-Za-z0-9_.-]+$ ]] && [[ "$agent" != .* ]] || agent="unknown"
area="${P4_AGENT_SCRATCH:-$agent}"                  # the agent's private subdirectory of every per-agent area (launcher --scratch)
[[ "$area" =~ ^[A-Za-z0-9_.-]+$ ]] && [[ "$area" != .* ]] || area="$agent"

# --ps / --stop act on the CALLING agent's containers only (review F round 3b, NF-3): the agent label is the launcher's
# P4_AGENT_NAME, which the host guard never lets an agent assign
if [ "${1:-}" = "--ps" ]; then
  exec "$DOCKER" ps --filter "label=brainir.p4.room=$ROOM_NAME" --filter "label=brainir.p4.agent=$agent" \
    --format 'table {{.ID}}\t{{.Names}}\t{{.RunningFor}}\t{{.Status}}'
fi
if [ "${1:-}" = "--stop" ]; then
  [ $# -eq 2 ] || die "usage: sbx --stop <container id or name>"
  [[ "$2" =~ ^[A-Za-z0-9_.-]+$ ]] || die "invalid container reference"
  lbl=$("$DOCKER" inspect --format '{{index .Config.Labels "brainir.p4.room"}}|{{index .Config.Labels "brainir.p4.agent"}}' "$2" \
        2>/dev/null || true)
  [ "$lbl" = "$ROOM_NAME|$agent" ] || die "not one of your sandbox containers in this room"
  exec "$DOCKER" stop --timeout 10 "$2"
fi
[ $# -ge 1 ] || die "usage: sbx <command> [args...]   (e.g. sbx python runs/<prefix>/exp.py)"
case "$1" in -*) die "the first argument is the command to run in the sandbox (options belong to that command)";; esac

here="$(pwd -P)"
shopt -s nocasematch
case "$here" in
  "$ROOM_POSIX") rel="" ;;
  "$ROOM_POSIX"/*) rel="${here:${#ROOM_POSIX}}" ;;
  *) die "run sbx from inside the room" ;;
esac
shopt -u nocasematch

is_top_ro() {
  local n="${1,,}" r
  for r in "${RO_TOPS[@]}" "${AGENT_AREAS[@]}" "${OWNED_AREAS[@]}"; do [ "$n" = "${r,,}" ] && return 0; done
  return 1
}
safe_name() { [[ "$1" =~ ^[A-Za-z0-9._@+\ -]+$ ]] && [[ "$1" != *,* ]]; }

mounts=(--mount "type=bind,source=$ROOM_MOUNT,target=/room,readonly")
for p in "${RW_PATHS[@]}"; do
  [ -d "$ROOM_POSIX/$p" ] && [ ! -L "$ROOM_POSIX/$p" ] || die "work area $p is missing: ask the orchestrator to --sync the room"
  mounts+=(--mount "type=bind,source=$ROOM_MOUNT/$p,target=/room/$p")
done
if [ "$FREE_ROOM" = 1 ]; then
  # a free room: every top-level entry that is not the orchestrator's is the agent's work area (the room root itself stays
  # read-only: new top-level files and directories are created on the host first, e.g. mkdir results)
  shopt -s dotglob nullglob
  for e in "$ROOM_POSIX"/*; do
    n="${e##*/}"
    is_top_ro "$n" && continue
    [ -L "$e" ] && die "the room holds a link at its root ($n): report it to the orchestrator"
    safe_name "$n" || die "top-level name not allowed in the sandbox: rename it (letters, digits, . _ - @ + space)"
    mounts+=(--mount "type=bind,source=$ROOM_MOUNT/$n,target=/room/$n")
  done
  shopt -u dotglob nullglob
fi
for a in "${AGENT_AREAS[@]}"; do
  [ -d "$ROOM_POSIX/$a" ] || die "work area $a is missing: ask the orchestrator to --sync the room"
  mkdir -p "$ROOM_POSIX/$a/$area"
  [ ! -L "$ROOM_POSIX/$a/$area" ] || die "$a/$area is a link: report it to the orchestrator"
  mounts+=(--mount "type=tmpfs,target=/room/$a,tmpfs-size=1m,tmpfs-mode=555" --mount "type=bind,source=$ROOM_MOUNT/$a/$area,target=/room/$a/$area")
done
for a in "${OWNED_AREAS[@]}"; do
  [ -d "$ROOM_POSIX/$a" ] && [ ! -L "$ROOM_POSIX/$a" ] || die "work area $a is missing: ask the orchestrator to --sync the room"
  mkdir -p "$ROOM_POSIX/$a/$area"
  [ ! -L "$ROOM_POSIX/$a/$area" ] || die "$a/$area is a link: report it to the orchestrator"
  mounts+=(--mount "type=bind,source=$ROOM_MOUNT/$a/$area,target=/room/$a/$area")
done

pytest_opts=()
[ "$FREE_ROOM" = 1 ] || pytest_opts=(-e "PYTEST_ADDOPTS=-p no:cacheprovider")
# the simulation-service identity token: the launcher's file outside the room for this agent (older launches: the environment);
# exported for `-e NAME`, which copies the value into the container without putting it on the command line
sim_opts=()
tok=""
if [ -n "$TOKEN_DIR" ] && [ -f "$TOKEN_DIR/$area.token" ]; then tok="$(tr -cd '0-9a-f' < "$TOKEN_DIR/$area.token")"; fi
[ -n "$tok" ] || tok="${P4_SIM_TOKEN:-}"
if [[ "$tok" =~ ^[0-9a-f]{64}$ ]]; then export P4_SIM_TOKEN="$tok"; sim_opts=(-e P4_SIM_TOKEN); fi
unset tok

# no process id in the name (review F round 3c, NF3c-1): the client's process id lives only in the container's label
name="p4sbx-${ROOM_NAME}-${agent}-$(printf '%04x%04x%04x' "$RANDOM" "$RANDOM" "$RANDOM")"
create_args=(--rm -i --pull never --name "$name" \
  --network none --read-only --tmpfs /tmp:rw,exec,nosuid,size=4g \
  --cap-drop ALL --security-opt no-new-privileges --security-opt "seccomp=$SECCOMP" --pids-limit 512 --user 1000:1000 \
  --cpus "$cpus" --memory "${mem}g" --memory-swap "${mem}g" \
  --label "brainir.p4.room=$ROOM_NAME" --label "brainir.p4.agent=$agent" --label "brainir.p4.sandbox=1" --label "brainir.p4.client=$$" \
  "${mounts[@]}" -w "/room$rel" \
  -e PYTHONPATH=/room/src -e PYTHONDONTWRITEBYTECODE=1 -e PYTHONPYCACHEPREFIX=/tmp/pyc "${pytest_opts[@]}" "${sim_opts[@]}" \
  -e P4_SANDBOX=1 -e "P4_AGENT_NAME=$agent" -e "P4_AGENT_SCRATCH=$area" -e "P4_SBX_CPUS=$cpus" \
  -e "OMP_NUM_THREADS=$threads" -e "MKL_NUM_THREADS=$threads" -e "OPENBLAS_NUM_THREADS=$threads" \
  "$IMAGE" timeout --signal=TERM --kill-after=30 "$tmo" "$@")

# ---- the machine-wide slot: a short critical section (atomic mkdir) counts the sandbox containers of EVERY room (name prefix
# p4sbx-, any state but exited) and the host's free memory, and CREATES the container inside it, so the created container holds the
# slot before the next wrapper looks; the container is then started attached (exit code = the command's).
free_gb() { awk '/^MemFree:/ { printf "%d", $2 / 1048576 }' /proc/meminfo 2>/dev/null || echo 0; }
age_s() {  # seconds since a container was created (0 when unknown, so an unreadable container counts as a holder)
  local cr c
  cr=$("$DOCKER" inspect --format '{{.Created}}' "$1" 2>/dev/null || echo "")
  c="${cr%Z}"; c="${c%.*}"
  [ -n "$c" ] || { echo 0; return; }
  echo $(( $(date -u +%s) - $(date -u -d "${c}Z" +%s 2>/dev/null || date -u +%s) ))
}
sandboxes() {
  # sandbox containers that hold a slot: running ones whose sbx client is alive, and ones created within the last 120 s. A container
  # older than 60 s whose client process (label brainir.p4.client = the wrapper's process id, alive for as long as the attached
  # client runs) is gone was orphaned by a killed tool call: it is stopped and logged (it would hold the machine's slot until its
  # timeout). Older created-but-never-started containers are removed.
  local id st cl
  "$DOCKER" ps -a --filter "name=^p4sbx-" --format '{{.ID}} {{.State}} {{.Label "brainir.p4.client"}}' 2>/dev/null |
  while read -r id st cl; do
    case "$st" in
      running|restarting|paused|removing)
        if [[ "$cl" =~ ^[0-9]+$ ]] && ! kill -0 "$cl" 2>/dev/null && [ "$(age_s "$id")" -gt 60 ]; then
          echo "$(date -u +%FT%TZ) stopped orphan $id (client $cl gone)" >> "$SLOT_DIR/reaped.log" 2>/dev/null || true
          "$DOCKER" stop --timeout 5 "$id" >/dev/null 2>&1 || true
        else
          echo "$id"
        fi ;;
      created)
        if [ "$(age_s "$id")" -gt 120 ]; then "$DOCKER" rm -f "$id" >/dev/null 2>&1 || true; else echo "$id"; fi ;;
    esac
  done
}
mkdir -p "$SLOT_DIR" 2>/dev/null || true
mutex="$SLOT_DIR/mutex"
start_t=$(date -u +%s); said=0
while :; do
  if [ -d "$mutex" ] && [ -n "$(find "$mutex" -maxdepth 0 -mmin +2 2>/dev/null)" ]; then rmdir "$mutex" 2>/dev/null || true; fi
  if mkdir "$mutex" 2>/dev/null; then
    holders=$(sandboxes | wc -l | tr -d ' ')
    fg=$(free_gb)
    if [ "$holders" -lt "$MAX_SLOTS" ] && [ "$fg" -ge "$MIN_FREE_GB" ]; then
      if ! cid=$("$DOCKER" create "${create_args[@]}"); then rmdir "$mutex" 2>/dev/null || true; die "could not create the sandbox container"; fi
      rmdir "$mutex" 2>/dev/null || true
      exec "$DOCKER" start -ai "$cid"
    fi
    rmdir "$mutex" 2>/dev/null || true
  else
    holders="?"; fg=$(free_gb)
  fi
  waited=$(( $(date -u +%s) - start_t ))
  if [ "$waited" -ge "$wait_s" ]; then
    # never another agent's or room's container name (review F round 3c, NF3c-1): only how long the slot has been busy, and the
    # caller's OWN containers (which it may stop with sbx --stop)
    busy=$("$DOCKER" ps --filter "name=^p4sbx-" --format '{{.RunningFor}}' 2>/dev/null | tail -1)
    mine=$("$DOCKER" ps --filter "label=brainir.p4.room=$ROOM_NAME" --filter "label=brainir.p4.agent=$agent" \
           --format '{{.Names}} ({{.RunningFor}})' 2>/dev/null | tr '\n' ' ')
    echo "sbx: no sandbox slot after ${waited} s: this machine runs ${MAX_SLOTS} sandbox at a time and starts one only with >= ${MIN_FREE_GB} GB free (now ${fg} GB free; the slot is busy since ${busy:-an unknown time}${mine:+; YOURS: $mine}). Retry later; run long work on the remote runner; stop your own stale container with sbx --stop." >&2
    exit 75
  fi
  if [ "$said" = 0 ]; then echo "sbx: waiting for the machine's sandbox slot (${MAX_SLOTS} at a time, >= ${MIN_FREE_GB} GB free; up to ${wait_s} s)..." >&2; said=1; fi
  sleep 3
done
